#include "../include/codec.h"
#include "../include/event_listener.hpp"
#include "../include/fast_book.hpp"
#include "../include/types.h"
#include "messages.h"
#include <cstring>
#include <filesystem>
#include <fstream>
#include <gtest/gtest.h>
#include <vector>

// Integration test: replay a pre-generated ITCH fixture through FastBook and
// compare output against the oracle reconstructor's expected state.
//
// Fixture files live in engine/tests/fixtures/ and are generated by:
//   itch_ingest <itch_file.bin> <SYMBOL> engine/tests/fixtures/
//
// The test skips gracefully if the fixture directory is empty, so CI passes
// before fixtures are generated for the first time.

using namespace lob;
using namespace lob::codec;
using namespace lob::proto;

namespace {

const std::filesystem::path FIXTURE_DIR =
    std::filesystem::path(__FILE__).parent_path() / "fixtures";

bool fixtures_exist() {
    return std::filesystem::exists(FIXTURE_DIR / "fixture.bin") &&
           std::filesystem::exists(FIXTURE_DIR / "expected_fills.bin");
}

// ── Helpers ───────────────────────────────────────────────────────────────────

struct FillRecord {
    uint64_t passive_id;
    uint64_t aggressor_id;
    uint64_t price;
    uint32_t qty;
};

class FillCollector : public EventListener {
public:
    std::vector<FillRecord> fills;

    void on_order_added(const Order &) override {}
    void on_order_canceled(OrderId, Quantity, Quantity) override {}
    void on_order_modified(OrderId, Quantity) override {}
    void on_order_filled(OrderId aggressor, OrderId passive,
                         Price price, Quantity qty) override {
        fills.push_back({passive, aggressor, price.price, qty.quantity});
    }
};

// Replay fixture.bin through book. Mirrors lob_runner's run() loop.
void replay(FastBook &book, const std::filesystem::path &path) {
    std::ifstream in(path, std::ios::binary);
    ASSERT_TRUE(in.is_open()) << "cannot open " << path;

    while (true) {
        uint8_t type_byte;
        if (!in.read(reinterpret_cast<char *>(&type_byte), 1)) break;

        MsgType type = static_cast<MsgType>(type_byte);
        size_t  size = msg_size(type);
        if (size == 0) break;

        std::byte buf[MAX_MSG_SIZE];
        buf[0] = static_cast<std::byte>(type_byte);
        if (size > 1 && !in.read(reinterpret_cast<char *>(buf + 1), size - 1)) break;

        auto msg = decode_inbound(buf, size);
        if (!msg) continue;

        std::visit([&](auto &m) {
            using T = std::decay_t<decltype(m)>;
            if constexpr (std::is_same_v<T, EnterOrder>) {
                Order order(m.order_id, Price(m.price), m.seq_num,
                            Quantity(m.quantity),
                            m.side == 0 ? Side::BUY : Side::SELL);
                book.add(order);
            } else if constexpr (std::is_same_v<T, CancelOrder>) {
                if (m.quantity == 0)
                    book.cancel(m.order_id);
                else
                    book.modify(m.order_id, Quantity(m.remaining_qty));
            } else if constexpr (std::is_same_v<T, ReplaceOrder>) {
                book.cancel(m.order_id);
            }
        }, *msg);
    }
}

// Read all Trade records from expected_fills.bin.
std::vector<FillRecord> read_expected_fills(const std::filesystem::path &path) {
    std::ifstream in(path, std::ios::binary);
    std::vector<FillRecord> out;
    Trade t{};
    while (in.read(reinterpret_cast<char *>(&t), sizeof(t)))
        out.push_back({t.passive_id, t.aggressor_id, t.price, t.qty});
    return out;
}

// Snapshot entry: side (0=bid,1=ask), price, total qty at that level.
struct SnapEntry { uint8_t side; uint64_t price; uint32_t qty; };

std::vector<SnapEntry> read_snapshot(const std::filesystem::path &path) {
    std::ifstream in(path, std::ios::binary);
    std::vector<SnapEntry> out;
    while (in) {
        SnapEntry e{};
        if (!in.read(reinterpret_cast<char *>(&e.side),  1)) break;
        if (!in.read(reinterpret_cast<char *>(&e.price), 8)) break;
        if (!in.read(reinterpret_cast<char *>(&e.qty),   4)) break;
        out.push_back(e);
    }
    return out;
}

const Price  MIN_PRICE  {1};
const Price  MAX_PRICE  {9'999'999};
const size_t MAX_ORDERS  = 1'000'000;

} // namespace

// ── Tests ─────────────────────────────────────────────────────────────────────

TEST(ItchReplay, FixtureFilesPresent) {
    if (!fixtures_exist()) {
        GTEST_SKIP() << "ITCH fixtures not found in " << FIXTURE_DIR
                     << " — run `itch_ingest <itch.bin> <SYM> engine/tests/fixtures/` first";
    }
    auto fixture_size = std::filesystem::file_size(FIXTURE_DIR / "fixture.bin");
    auto fills_size   = std::filesystem::file_size(FIXTURE_DIR / "expected_fills.bin");

    EXPECT_GT(fixture_size, 0u);
    EXPECT_GT(fills_size,   0u);
    // All inbound messages are 32 bytes; Trade records are 48 bytes.
    EXPECT_EQ(fixture_size % sizeof(EnterOrder), 0u)
        << "fixture.bin size is not a multiple of 32";
    EXPECT_EQ(fills_size % sizeof(Trade), 0u)
        << "expected_fills.bin size is not a multiple of 48";

    if (std::filesystem::exists(FIXTURE_DIR / "expected_book_snapshot.bin")) {
        auto snap_size = std::filesystem::file_size(FIXTURE_DIR / "expected_book_snapshot.bin");
        EXPECT_EQ(snap_size % 13u, 0u) << "snapshot size is not a multiple of 13";
        EXPECT_LE(snap_size, 20u * 13u) << "snapshot has more than 20 levels";
    }
}

TEST(ItchReplay, FillsMatchExpected) {
    if (!fixtures_exist()) {
        GTEST_SKIP() << "fixtures not present";
    }

    FillCollector collector;
    FastBook book(&collector, MIN_PRICE, MAX_PRICE, MAX_ORDERS);
    replay(book, FIXTURE_DIR / "fixture.bin");

    auto expected = read_expected_fills(FIXTURE_DIR / "expected_fills.bin");

    ASSERT_EQ(collector.fills.size(), expected.size())
        << "fill count mismatch: engine=" << collector.fills.size()
        << " expected=" << expected.size();

    for (size_t i = 0; i < expected.size(); ++i) {
        SCOPED_TRACE("fill index " + std::to_string(i));
        EXPECT_EQ(collector.fills[i].passive_id, expected[i].passive_id);
        EXPECT_EQ(collector.fills[i].price,      expected[i].price);
        EXPECT_EQ(collector.fills[i].qty,        expected[i].qty);
        // aggressor_id not compared: ITCH 'E' messages don't carry aggressor ref,
        // so expected_fills.bin always has aggressor_id=0.
    }
}

TEST(ItchReplay, FinalBookStateMatchesExpected) {
    if (!fixtures_exist()) {
        GTEST_SKIP() << "fixtures not present";
    }
    const auto snap_path = FIXTURE_DIR / "expected_book_snapshot.bin";
    if (!std::filesystem::exists(snap_path)) {
        GTEST_SKIP() << "expected_book_snapshot.bin not present";
    }

    FillCollector collector;
    FastBook book(&collector, MIN_PRICE, MAX_PRICE, MAX_ORDERS);
    replay(book, FIXTURE_DIR / "fixture.bin");

    auto snap = read_snapshot(snap_path);
    ASSERT_FALSE(snap.empty()) << "snapshot file is empty";

    for (size_t i = 0; i < snap.size(); ++i) {
        SCOPED_TRACE("snapshot level " + std::to_string(i));
        Side side = snap[i].side == 0 ? Side::BUY : Side::SELL;
        Quantity actual = book.total_quantity_at_price(Price(snap[i].price), side);
        EXPECT_EQ(actual.quantity, snap[i].qty)
            << (snap[i].side == 0 ? "BID" : "ASK")
            << " @ price " << snap[i].price;
    }
}
